github:
  repo_url: https://github.com/thomaseleff/bunsen
  main_branch: main
  coding_trigger_label: ready-for-dev
  coding_workflow_filename: swe_agent.yaml

llm:
  bunsen_model_name: openai/gpt-5
  beaker_model_name: openai/o4-mini
